import { Repository } from 'typeorm';
import { CatalogueItem } from '../entities';

export const mockCatalogueItems = [
  // Breakfast / Brunch (3)
  {
    id: 1,
    name: 'The Morning Sun Café',
    description: 'Artisanal pastries and bespoke coffee blends.',
    price: 45,
    categoryGroup: 'dining',
    tags: ['casual', 'quiet'],
    openFrom: '07:00',
    openTo: '11:00',
    durationMin: 60,
    imageUrl: null,
  },
  {
    id: 2,
    name: 'Crystal Brasserie Brunch',
    description: 'Opulent buffet with champagne.',
    price: 120,
    categoryGroup: 'dining',
    tags: ['fine_dining', 'social', 'lively'],
    openFrom: '09:00',
    openTo: '14:00',
    durationMin: 90,
    imageUrl: null,
  },
  {
    id: 3,
    name: 'Green Haven Juice Bar',
    description: 'Freshly pressed juices and healthy bowls.',
    price: 30,
    categoryGroup: 'dining',
    tags: ['wellness', 'casual', 'quiet'],
    openFrom: '06:00',
    openTo: '15:00',
    durationMin: 30,
    imageUrl: null,
  },

  // Dinner (5)
  {
    id: 4,
    name: 'Ember & Oak',
    description: 'Wood-fired steaks in a dark, romantic setting.',
    price: 250,
    categoryGroup: 'dining',
    tags: ['fine_dining', 'romantic', 'luxury'],
    openFrom: '17:00',
    openTo: '23:00',
    durationMin: 120,
    imageUrl: null,
  },
  {
    id: 5,
    name: 'Oceanic Tasting Room',
    description: '12-course seafood tasting menu.',
    price: 350,
    categoryGroup: 'dining',
    tags: ['fine_dining', 'luxury', 'wine', 'quiet'],
    openFrom: '18:00',
    openTo: '22:30',
    durationMin: 150,
    imageUrl: null,
  },
  {
    id: 6,
    name: 'Neon Noodle Bar',
    description: 'Lively, casual Asian street food.',
    price: 50,
    categoryGroup: 'dining',
    tags: ['casual', 'lively', 'social'],
    openFrom: '11:00',
    openTo: '02:00',
    durationMin: 45,
    imageUrl: null,
  },
  {
    id: 7,
    name: 'Vine Street Grill',
    description: 'Classic American dishes with an extensive wine list.',
    price: 150,
    categoryGroup: 'dining',
    tags: ['fine_dining', 'wine', 'romantic'],
    openFrom: '17:30',
    openTo: '22:00',
    durationMin: 90,
    imageUrl: null,
  },
  {
    id: 8,
    name: 'The Secret Garden Trattoria',
    description: 'Hidden outdoor Italian dining experience.',
    price: 180,
    categoryGroup: 'dining',
    tags: ['romantic', 'quiet', 'fine_dining'],
    openFrom: '18:00',
    openTo: '23:00',
    durationMin: 120,
    imageUrl: null,
  },

  // Bars (3)
  {
    id: 9,
    name: 'Golden Hour Terrace Bar',
    description: 'Rooftop cocktails overlooking the strip.',
    price: 80,
    categoryGroup: 'bar',
    tags: ['sunset', 'cocktails', 'social', 'romantic'],
    openFrom: '16:00',
    openTo: '01:00',
    durationMin: 90,
    imageUrl: null,
  },
  {
    id: 10,
    name: 'The Alchemist Speakeasy',
    description: 'Experimental mixology in a hidden room.',
    price: 100,
    categoryGroup: 'bar',
    tags: ['cocktails', 'quiet', 'nightlife'],
    openFrom: '19:00',
    openTo: '02:00',
    durationMin: 90,
    imageUrl: null,
  },
  {
    id: 11,
    name: 'Blue Note Jazz Lounge',
    description: 'Classic cocktails and live jazz bands.',
    price: 120,
    categoryGroup: 'bar',
    tags: ['live_music', 'jazz', 'nightlife', 'social'],
    openFrom: '20:00',
    openTo: '03:00',
    durationMin: 120,
    imageUrl: null,
  },

  // Spa (3) + Upgrades (2)
  {
    id: 12,
    name: 'Serenity Stone Massage',
    description: 'Hot stone therapy for ultimate relaxation.',
    price: 200,
    categoryGroup: 'spa',
    tags: ['spa', 'wellness', 'quiet', 'luxury'],
    openFrom: '08:00',
    openTo: '20:00',
    durationMin: 60,
    imageUrl: null,
  },
  {
    id: 13,
    name: 'Aura Cleansing Facial',
    description: 'Rejuvenating organic facial treatment.',
    price: 180,
    categoryGroup: 'spa',
    tags: ['spa', 'wellness', 'quiet'],
    openFrom: '08:00',
    openTo: '20:00',
    durationMin: 60,
    imageUrl: null,
  },
  {
    id: 14,
    name: 'Couples Retreat Package',
    description: 'Side-by-side massage with private bath.',
    price: 450,
    categoryGroup: 'spa',
    tags: ['spa', 'wellness', 'romantic', 'luxury'],
    openFrom: '08:00',
    openTo: '20:00',
    durationMin: 90,
    imageUrl: null,
  },
  {
    id: 15,
    name: 'Extended 30-Min Massage',
    description: 'Add 30 extra minutes to your treatment.',
    price: 80,
    categoryGroup: 'spa',
    tags: ['spa', 'wellness', 'luxury'],
    openFrom: '08:00',
    openTo: '20:00',
    durationMin: 30,
    imageUrl: null,
    upsellOfId: 12,
  },
  {
    id: 16,
    name: 'Champagne & Truffles Spa Upgrade',
    description: 'Enjoy champagne and truffles after your facial.',
    price: 100,
    categoryGroup: 'spa',
    tags: ['spa', 'luxury', 'romantic'],
    openFrom: '08:00',
    openTo: '20:00',
    durationMin: 30,
    imageUrl: null,
    upsellOfId: 13,
  },

  // Pool Day (1) + Upgrade (1)
  {
    id: 17,
    name: 'Oasis Pool Day Pass',
    description: 'Access to the luxury resort pool.',
    price: 50,
    categoryGroup: 'experience',
    tags: ['pool', 'social', 'casual'],
    openFrom: '09:00',
    openTo: '19:00',
    durationMin: 180,
    imageUrl: null,
  },
  {
    id: 18,
    name: 'Private Poolside Cabana',
    description: 'Reserved cabana with dedicated service.',
    price: 300,
    categoryGroup: 'experience',
    tags: ['pool', 'luxury', 'social'],
    openFrom: '09:00',
    openTo: '19:00',
    durationMin: 180,
    imageUrl: null,
    upsellOfId: 17,
  },

  // Shows (2)
  {
    id: 19,
    name: 'Illusions of Grandeur',
    description: 'A mind-bending magic spectacular.',
    price: 150,
    categoryGroup: 'nightlife',
    tags: ['nightlife', 'social', 'lively'],
    openFrom: '19:30',
    openTo: '21:30',
    durationMin: 120,
    imageUrl: null,
  },
  {
    id: 20,
    name: 'Acrobatic Symphony',
    description: 'Breathtaking aerial acts set to live orchestral music.',
    price: 200,
    categoryGroup: 'nightlife',
    tags: ['nightlife', 'romantic', 'luxury'],
    openFrom: '21:00',
    openTo: '23:00',
    durationMin: 120,
    imageUrl: null,
  },

  // Nightlife (2)
  {
    id: 21,
    name: 'Velvet Room Club',
    description: 'High-energy nightclub with international DJs.',
    price: 150,
    categoryGroup: 'nightlife',
    tags: ['nightlife', 'social', 'lively'],
    openFrom: '22:30',
    openTo: '04:00',
    durationMin: 180,
    imageUrl: null,
  },
  {
    id: 22,
    name: 'Midnight Jazz Sessions',
    description: 'Late-night impromptu jazz performances.',
    price: 80,
    categoryGroup: 'nightlife',
    tags: ['nightlife', 'live_music', 'jazz', 'quiet'],
    openFrom: '23:00',
    openTo: '03:00',
    durationMin: 120,
    imageUrl: null,
  },

  // Fitness & Golf
  {
    id: 23,
    name: 'Sunrise Yoga on the Deck',
    description: 'Guided yoga session as the sun rises.',
    price: 40,
    categoryGroup: 'fitness',
    tags: ['wellness', 'fitness', 'quiet'],
    openFrom: '06:30',
    openTo: '07:30',
    durationMin: 60,
    imageUrl: null,
  },
  {
    id: 24,
    name: 'Desert Pines Golf Course 18 Holes',
    description: 'Premium 18-hole championship golf course.',
    price: 250,
    categoryGroup: 'experience',
    tags: ['golf', 'social', 'luxury'],
    openFrom: '07:00',
    openTo: '15:00',
    durationMin: 240,
    imageUrl: null,
  },

  // Experiences & Misc
  {
    id: 25,
    name: 'Helicopter Sunset Tour',
    description: 'A breathtaking aerial view of the strip at dusk.',
    price: 400,
    categoryGroup: 'experience',
    tags: ['sunset', 'adventure', 'romantic', 'luxury'],
    openFrom: '17:30',
    openTo: '18:30',
    durationMin: 60,
    imageUrl: null,
  },
  {
    id: 26,
    name: 'Master Sommelier Wine Tasting',
    description: 'Exclusive tasting of rare vintages.',
    price: 220,
    categoryGroup: 'experience',
    tags: ['wine', 'luxury', 'quiet'],
    openFrom: '15:00',
    openTo: '17:00',
    durationMin: 120,
    imageUrl: null,
  },

  // Dining Upgrades
  {
    id: 27,
    name: 'Private Balcony Dining Upgrade',
    description: 'Move your dinner to a private balcony with a view.',
    price: 150,
    categoryGroup: 'dining',
    tags: ['luxury', 'romantic'],
    openFrom: '17:00',
    openTo: '23:00',
    durationMin: 0,
    imageUrl: null,
    upsellOfId: 4,
  },

  // In-Room
  {
    id: 28,
    name: 'Midnight In-Room Feast',
    description: 'Late-night gourmet room service.',
    price: 100,
    categoryGroup: 'in_room',
    tags: ['casual', 'quiet'],
    openFrom: '00:00',
    openTo: '23:59',
    durationMin: 45,
    imageUrl: null,
  },

  // Shopping (2)
  {
    id: 29,
    name: 'Personal Shopper Experience',
    description: 'Guided tour of luxury boutiques with a stylist.',
    price: 500,
    categoryGroup: 'experience',
    tags: ['shopping', 'luxury', 'social'],
    openFrom: '10:00',
    openTo: '14:00',
    durationMin: 240,
    imageUrl: null,
  },
  {
    id: 30,
    name: 'Artisan Market Walk',
    description: 'Explore local crafts and unique souvenirs.',
    price: 0,
    categoryGroup: 'experience',
    tags: ['shopping', 'casual', 'adventure'],
    openFrom: '10:00',
    openTo: '18:00',
    durationMin: 90,
    imageUrl: null,
  },
];

export async function seedCatalogue(repo: Repository<CatalogueItem>) {
  await repo.query('SET FOREIGN_KEY_CHECKS = 0');
  await repo.clear();
  await repo.query('SET FOREIGN_KEY_CHECKS = 1');

  for (const item of mockCatalogueItems) {
    const entity = repo.create({
      id: item.id,
      name: item.name,
      description: item.description,
      price: item.price,
      details: {
        categoryGroup: item.categoryGroup,
        tags: item.tags,
        openFrom: item.openFrom,
        openTo: item.openTo,
        durationMin: item.durationMin,
        upsellOfId: (item as any).upsellOfId,
        imageUrl: item.imageUrl,
      },
    });
    await repo.save(entity);
  }
}
